//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingMarket.Web.BuyOrderDetailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BuyOrderDetailService.IBuyOrderDetailService")]
    public interface IBuyOrderDetailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuyOrderDetailService/GetBuyOrderDetailsByBuyOrderId", ReplyAction="http://tempuri.org/IBuyOrderDetailService/GetBuyOrderDetailsByBuyOrderIdResponse")]
        System.Collections.Generic.List<KingMarket.Model.Models.BuyOrderDetail> GetBuyOrderDetailsByBuyOrderId(int buyOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuyOrderDetailService/GetBuyOrderDetailsByBuyOrderId", ReplyAction="http://tempuri.org/IBuyOrderDetailService/GetBuyOrderDetailsByBuyOrderIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.BuyOrderDetail>> GetBuyOrderDetailsByBuyOrderIdAsync(int buyOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuyOrderDetailService/GetBuyOrderDetail", ReplyAction="http://tempuri.org/IBuyOrderDetailService/GetBuyOrderDetailResponse")]
        KingMarket.Model.Models.BuyOrderDetail GetBuyOrderDetail(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuyOrderDetailService/GetBuyOrderDetail", ReplyAction="http://tempuri.org/IBuyOrderDetailService/GetBuyOrderDetailResponse")]
        System.Threading.Tasks.Task<KingMarket.Model.Models.BuyOrderDetail> GetBuyOrderDetailAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuyOrderDetailServiceChannel : KingMarket.Web.BuyOrderDetailService.IBuyOrderDetailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuyOrderDetailServiceClient : System.ServiceModel.ClientBase<KingMarket.Web.BuyOrderDetailService.IBuyOrderDetailService>, KingMarket.Web.BuyOrderDetailService.IBuyOrderDetailService {
        
        public BuyOrderDetailServiceClient() {
        }
        
        public BuyOrderDetailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuyOrderDetailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuyOrderDetailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuyOrderDetailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KingMarket.Model.Models.BuyOrderDetail> GetBuyOrderDetailsByBuyOrderId(int buyOrderId) {
            return base.Channel.GetBuyOrderDetailsByBuyOrderId(buyOrderId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.BuyOrderDetail>> GetBuyOrderDetailsByBuyOrderIdAsync(int buyOrderId) {
            return base.Channel.GetBuyOrderDetailsByBuyOrderIdAsync(buyOrderId);
        }
        
        public KingMarket.Model.Models.BuyOrderDetail GetBuyOrderDetail(int id) {
            return base.Channel.GetBuyOrderDetail(id);
        }
        
        public System.Threading.Tasks.Task<KingMarket.Model.Models.BuyOrderDetail> GetBuyOrderDetailAsync(int id) {
            return base.Channel.GetBuyOrderDetailAsync(id);
        }
    }
}
