//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingMarket.Web.SaleOrderDetailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaleOrderDetailService.ISaleOrderDetailService")]
    public interface ISaleOrderDetailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleOrderDetailService/GetSaleOrderDetailsBySaleOrderId", ReplyAction="http://tempuri.org/ISaleOrderDetailService/GetSaleOrderDetailsBySaleOrderIdRespon" +
            "se")]
        System.Collections.Generic.List<KingMarket.Model.Models.SaleOrderDetail> GetSaleOrderDetailsBySaleOrderId(int saleOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleOrderDetailService/GetSaleOrderDetailsBySaleOrderId", ReplyAction="http://tempuri.org/ISaleOrderDetailService/GetSaleOrderDetailsBySaleOrderIdRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.SaleOrderDetail>> GetSaleOrderDetailsBySaleOrderIdAsync(int saleOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleOrderDetailService/GetSaleOrderDetail", ReplyAction="http://tempuri.org/ISaleOrderDetailService/GetSaleOrderDetailResponse")]
        KingMarket.Model.Models.SaleOrderDetail GetSaleOrderDetail(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleOrderDetailService/GetSaleOrderDetail", ReplyAction="http://tempuri.org/ISaleOrderDetailService/GetSaleOrderDetailResponse")]
        System.Threading.Tasks.Task<KingMarket.Model.Models.SaleOrderDetail> GetSaleOrderDetailAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaleOrderDetailServiceChannel : KingMarket.Web.SaleOrderDetailService.ISaleOrderDetailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaleOrderDetailServiceClient : System.ServiceModel.ClientBase<KingMarket.Web.SaleOrderDetailService.ISaleOrderDetailService>, KingMarket.Web.SaleOrderDetailService.ISaleOrderDetailService {
        
        public SaleOrderDetailServiceClient() {
        }
        
        public SaleOrderDetailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaleOrderDetailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleOrderDetailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleOrderDetailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KingMarket.Model.Models.SaleOrderDetail> GetSaleOrderDetailsBySaleOrderId(int saleOrderId) {
            return base.Channel.GetSaleOrderDetailsBySaleOrderId(saleOrderId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.SaleOrderDetail>> GetSaleOrderDetailsBySaleOrderIdAsync(int saleOrderId) {
            return base.Channel.GetSaleOrderDetailsBySaleOrderIdAsync(saleOrderId);
        }
        
        public KingMarket.Model.Models.SaleOrderDetail GetSaleOrderDetail(int id) {
            return base.Channel.GetSaleOrderDetail(id);
        }
        
        public System.Threading.Tasks.Task<KingMarket.Model.Models.SaleOrderDetail> GetSaleOrderDetailAsync(int id) {
            return base.Channel.GetSaleOrderDetailAsync(id);
        }
    }
}
