//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingMarket.Web.CustomerContactService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerContactService.ICustomerContactService")]
    public interface ICustomerContactService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/GetCustomerContacts", ReplyAction="http://tempuri.org/ICustomerContactService/GetCustomerContactsResponse")]
        System.Collections.Generic.List<KingMarket.Model.Models.CustomerContact> GetCustomerContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/GetCustomerContacts", ReplyAction="http://tempuri.org/ICustomerContactService/GetCustomerContactsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.CustomerContact>> GetCustomerContactsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/GetCustomerContact", ReplyAction="http://tempuri.org/ICustomerContactService/GetCustomerContactResponse")]
        KingMarket.Model.Models.CustomerContact GetCustomerContact(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/GetCustomerContact", ReplyAction="http://tempuri.org/ICustomerContactService/GetCustomerContactResponse")]
        System.Threading.Tasks.Task<KingMarket.Model.Models.CustomerContact> GetCustomerContactAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/CreateCustomerContact", ReplyAction="http://tempuri.org/ICustomerContactService/CreateCustomerContactResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KingMarket.Model.Models.GeneralException), Action="http://tempuri.org/ICustomerContactService/CreateCustomerContactGeneralExceptionF" +
            "ault", Name="GeneralException", Namespace="http://schemas.datacontract.org/2004/07/KingMarket.Model.Models")]
        void CreateCustomerContact(KingMarket.Model.Models.CustomerContact myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/CreateCustomerContact", ReplyAction="http://tempuri.org/ICustomerContactService/CreateCustomerContactResponse")]
        System.Threading.Tasks.Task CreateCustomerContactAsync(KingMarket.Model.Models.CustomerContact myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/EditCustomerContact", ReplyAction="http://tempuri.org/ICustomerContactService/EditCustomerContactResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KingMarket.Model.Models.GeneralException), Action="http://tempuri.org/ICustomerContactService/EditCustomerContactGeneralExceptionFau" +
            "lt", Name="GeneralException", Namespace="http://schemas.datacontract.org/2004/07/KingMarket.Model.Models")]
        void EditCustomerContact(KingMarket.Model.Models.CustomerContact myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/EditCustomerContact", ReplyAction="http://tempuri.org/ICustomerContactService/EditCustomerContactResponse")]
        System.Threading.Tasks.Task EditCustomerContactAsync(KingMarket.Model.Models.CustomerContact myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/DeleteCustomerContact", ReplyAction="http://tempuri.org/ICustomerContactService/DeleteCustomerContactResponse")]
        void DeleteCustomerContact(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContactService/DeleteCustomerContact", ReplyAction="http://tempuri.org/ICustomerContactService/DeleteCustomerContactResponse")]
        System.Threading.Tasks.Task DeleteCustomerContactAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerContactServiceChannel : KingMarket.Web.CustomerContactService.ICustomerContactService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerContactServiceClient : System.ServiceModel.ClientBase<KingMarket.Web.CustomerContactService.ICustomerContactService>, KingMarket.Web.CustomerContactService.ICustomerContactService {
        
        public CustomerContactServiceClient() {
        }
        
        public CustomerContactServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerContactServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerContactServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerContactServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KingMarket.Model.Models.CustomerContact> GetCustomerContacts() {
            return base.Channel.GetCustomerContacts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.CustomerContact>> GetCustomerContactsAsync() {
            return base.Channel.GetCustomerContactsAsync();
        }
        
        public KingMarket.Model.Models.CustomerContact GetCustomerContact(int id) {
            return base.Channel.GetCustomerContact(id);
        }
        
        public System.Threading.Tasks.Task<KingMarket.Model.Models.CustomerContact> GetCustomerContactAsync(int id) {
            return base.Channel.GetCustomerContactAsync(id);
        }
        
        public void CreateCustomerContact(KingMarket.Model.Models.CustomerContact myObject) {
            base.Channel.CreateCustomerContact(myObject);
        }
        
        public System.Threading.Tasks.Task CreateCustomerContactAsync(KingMarket.Model.Models.CustomerContact myObject) {
            return base.Channel.CreateCustomerContactAsync(myObject);
        }
        
        public void EditCustomerContact(KingMarket.Model.Models.CustomerContact myObject) {
            base.Channel.EditCustomerContact(myObject);
        }
        
        public System.Threading.Tasks.Task EditCustomerContactAsync(KingMarket.Model.Models.CustomerContact myObject) {
            return base.Channel.EditCustomerContactAsync(myObject);
        }
        
        public void DeleteCustomerContact(int id) {
            base.Channel.DeleteCustomerContact(id);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerContactAsync(int id) {
            return base.Channel.DeleteCustomerContactAsync(id);
        }
    }
}
