//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingMarket.Web.SupplierContactService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupplierContactService.ISupplierContactService")]
    public interface ISupplierContactService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/GetSupplierContacts", ReplyAction="http://tempuri.org/ISupplierContactService/GetSupplierContactsResponse")]
        System.Collections.Generic.List<KingMarket.Model.Models.SupplierContact> GetSupplierContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/GetSupplierContacts", ReplyAction="http://tempuri.org/ISupplierContactService/GetSupplierContactsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.SupplierContact>> GetSupplierContactsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/GetSupplierContact", ReplyAction="http://tempuri.org/ISupplierContactService/GetSupplierContactResponse")]
        KingMarket.Model.Models.SupplierContact GetSupplierContact(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/GetSupplierContact", ReplyAction="http://tempuri.org/ISupplierContactService/GetSupplierContactResponse")]
        System.Threading.Tasks.Task<KingMarket.Model.Models.SupplierContact> GetSupplierContactAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/CreateSupplierContact", ReplyAction="http://tempuri.org/ISupplierContactService/CreateSupplierContactResponse")]
        void CreateSupplierContact(KingMarket.Model.Models.SupplierContact myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/CreateSupplierContact", ReplyAction="http://tempuri.org/ISupplierContactService/CreateSupplierContactResponse")]
        System.Threading.Tasks.Task CreateSupplierContactAsync(KingMarket.Model.Models.SupplierContact myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/EditSupplierContact", ReplyAction="http://tempuri.org/ISupplierContactService/EditSupplierContactResponse")]
        void EditSupplierContact(KingMarket.Model.Models.SupplierContact myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/EditSupplierContact", ReplyAction="http://tempuri.org/ISupplierContactService/EditSupplierContactResponse")]
        System.Threading.Tasks.Task EditSupplierContactAsync(KingMarket.Model.Models.SupplierContact myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/DeleteSupplierContact", ReplyAction="http://tempuri.org/ISupplierContactService/DeleteSupplierContactResponse")]
        void DeleteSupplierContact(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierContactService/DeleteSupplierContact", ReplyAction="http://tempuri.org/ISupplierContactService/DeleteSupplierContactResponse")]
        System.Threading.Tasks.Task DeleteSupplierContactAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISupplierContactServiceChannel : KingMarket.Web.SupplierContactService.ISupplierContactService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierContactServiceClient : System.ServiceModel.ClientBase<KingMarket.Web.SupplierContactService.ISupplierContactService>, KingMarket.Web.SupplierContactService.ISupplierContactService {
        
        public SupplierContactServiceClient() {
        }
        
        public SupplierContactServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierContactServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierContactServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierContactServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KingMarket.Model.Models.SupplierContact> GetSupplierContacts() {
            return base.Channel.GetSupplierContacts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.SupplierContact>> GetSupplierContactsAsync() {
            return base.Channel.GetSupplierContactsAsync();
        }
        
        public KingMarket.Model.Models.SupplierContact GetSupplierContact(int id) {
            return base.Channel.GetSupplierContact(id);
        }
        
        public System.Threading.Tasks.Task<KingMarket.Model.Models.SupplierContact> GetSupplierContactAsync(int id) {
            return base.Channel.GetSupplierContactAsync(id);
        }
        
        public void CreateSupplierContact(KingMarket.Model.Models.SupplierContact myObject) {
            base.Channel.CreateSupplierContact(myObject);
        }
        
        public System.Threading.Tasks.Task CreateSupplierContactAsync(KingMarket.Model.Models.SupplierContact myObject) {
            return base.Channel.CreateSupplierContactAsync(myObject);
        }
        
        public void EditSupplierContact(KingMarket.Model.Models.SupplierContact myObject) {
            base.Channel.EditSupplierContact(myObject);
        }
        
        public System.Threading.Tasks.Task EditSupplierContactAsync(KingMarket.Model.Models.SupplierContact myObject) {
            return base.Channel.EditSupplierContactAsync(myObject);
        }
        
        public void DeleteSupplierContact(int id) {
            base.Channel.DeleteSupplierContact(id);
        }
        
        public System.Threading.Tasks.Task DeleteSupplierContactAsync(int id) {
            return base.Channel.DeleteSupplierContactAsync(id);
        }
    }
}
