//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingMarket.Web.DocumentTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentTypeService.IDocumentTypeService")]
    public interface IDocumentTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/GetDocumentTypes", ReplyAction="http://tempuri.org/IDocumentTypeService/GetDocumentTypesResponse")]
        System.Collections.Generic.List<KingMarket.Model.Models.DocumentType> GetDocumentTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/GetDocumentTypes", ReplyAction="http://tempuri.org/IDocumentTypeService/GetDocumentTypesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.DocumentType>> GetDocumentTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/GetDocumentType", ReplyAction="http://tempuri.org/IDocumentTypeService/GetDocumentTypeResponse")]
        KingMarket.Model.Models.DocumentType GetDocumentType(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/GetDocumentType", ReplyAction="http://tempuri.org/IDocumentTypeService/GetDocumentTypeResponse")]
        System.Threading.Tasks.Task<KingMarket.Model.Models.DocumentType> GetDocumentTypeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/CreateDocumentType", ReplyAction="http://tempuri.org/IDocumentTypeService/CreateDocumentTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KingMarket.Model.Models.GeneralException), Action="http://tempuri.org/IDocumentTypeService/CreateDocumentTypeGeneralExceptionFault", Name="GeneralException", Namespace="http://schemas.datacontract.org/2004/07/KingMarket.Model.Models")]
        void CreateDocumentType(KingMarket.Model.Models.DocumentType myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/CreateDocumentType", ReplyAction="http://tempuri.org/IDocumentTypeService/CreateDocumentTypeResponse")]
        System.Threading.Tasks.Task CreateDocumentTypeAsync(KingMarket.Model.Models.DocumentType myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/EditDocumentType", ReplyAction="http://tempuri.org/IDocumentTypeService/EditDocumentTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KingMarket.Model.Models.GeneralException), Action="http://tempuri.org/IDocumentTypeService/EditDocumentTypeGeneralExceptionFault", Name="GeneralException", Namespace="http://schemas.datacontract.org/2004/07/KingMarket.Model.Models")]
        void EditDocumentType(KingMarket.Model.Models.DocumentType myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/EditDocumentType", ReplyAction="http://tempuri.org/IDocumentTypeService/EditDocumentTypeResponse")]
        System.Threading.Tasks.Task EditDocumentTypeAsync(KingMarket.Model.Models.DocumentType myObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/DeleteDocumentType", ReplyAction="http://tempuri.org/IDocumentTypeService/DeleteDocumentTypeResponse")]
        void DeleteDocumentType(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentTypeService/DeleteDocumentType", ReplyAction="http://tempuri.org/IDocumentTypeService/DeleteDocumentTypeResponse")]
        System.Threading.Tasks.Task DeleteDocumentTypeAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentTypeServiceChannel : KingMarket.Web.DocumentTypeService.IDocumentTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentTypeServiceClient : System.ServiceModel.ClientBase<KingMarket.Web.DocumentTypeService.IDocumentTypeService>, KingMarket.Web.DocumentTypeService.IDocumentTypeService {
        
        public DocumentTypeServiceClient() {
        }
        
        public DocumentTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KingMarket.Model.Models.DocumentType> GetDocumentTypes() {
            return base.Channel.GetDocumentTypes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<KingMarket.Model.Models.DocumentType>> GetDocumentTypesAsync() {
            return base.Channel.GetDocumentTypesAsync();
        }
        
        public KingMarket.Model.Models.DocumentType GetDocumentType(int id) {
            return base.Channel.GetDocumentType(id);
        }
        
        public System.Threading.Tasks.Task<KingMarket.Model.Models.DocumentType> GetDocumentTypeAsync(int id) {
            return base.Channel.GetDocumentTypeAsync(id);
        }
        
        public void CreateDocumentType(KingMarket.Model.Models.DocumentType myObject) {
            base.Channel.CreateDocumentType(myObject);
        }
        
        public System.Threading.Tasks.Task CreateDocumentTypeAsync(KingMarket.Model.Models.DocumentType myObject) {
            return base.Channel.CreateDocumentTypeAsync(myObject);
        }
        
        public void EditDocumentType(KingMarket.Model.Models.DocumentType myObject) {
            base.Channel.EditDocumentType(myObject);
        }
        
        public System.Threading.Tasks.Task EditDocumentTypeAsync(KingMarket.Model.Models.DocumentType myObject) {
            return base.Channel.EditDocumentTypeAsync(myObject);
        }
        
        public void DeleteDocumentType(int id) {
            base.Channel.DeleteDocumentType(id);
        }
        
        public System.Threading.Tasks.Task DeleteDocumentTypeAsync(int id) {
            return base.Channel.DeleteDocumentTypeAsync(id);
        }
    }
}
